# Generated by Django 3.2.2 on 2021-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
